### ISSUE TITLE
What is  the 'Fori' doing?

### ISSUE THREAD

**Issue by techhasid** [ssochet/PCS-Class#1]
https://github.com/ssochet/PCS-Class/blob/802676f0c950782cefa8ee84f2c1236dc95b4415/JavaScript/HW_97_snake_ball/snake/snake.js#L128

I'm wondering why you needed the Fori statement on line 128, and the i-- on line 136. 
Also, the fori is set to <1, which means that it will happen only once anyway.

**Comment by ssochet** [comment]
If the apple's x and y landed on the snake then `i--`, `i` will be `0`,  which will cause the `for` loop to run again. This in turn will choose a new x and y for the apple. Otherwise, as you said the regular `for` loop behavior of `i++` will occur and `i` will be 1 so the `for` will end.
